scans: 11  # scan number or list of scan numbers
root_folder: "C:/Users/Jerome/Documents/data/CXIDB-I182/CH4760/"
# folder of the experiment, where all scans are stored
save_dir: "C:/Users/Jerome/Documents/data/CXIDB-I182/CH4760/test/"
# images will be saved here, leave it to None otherwise (default to data directory's
# parent). Provide a single path or a list of paths for multiple scans.
data_dir: "C:/Users/Jerome/Documents/data/CXIDB-I182/CH4760/S11/"
# leave None to use the beamline default, or provide the full path to the data. Provide
# a list of paths for multiple scans.
sample_name: "S"
# string in front of the scan number in the folder name.
reconstruction_files: None
# full path to the output of phase retrieval, or list of such paths if 'scans' is a
# list. Providing several reconstructions for each scan is not supported.
# If None an interactive window will open to choose a file.
comment: ""  # comment in filenames, should start with _
colormap: "turbo"  # "turbo", "custom" or colormap defined in the colorcet package
backend: "Qt5Agg"
# Backend used in script, change to "Agg" if you want to save the figures without
# showing them. Other possibilities are "Qt5Agg" (default) and
# "module://matplotlib_inline.backend_inline"
##########################################################
# parameters used when averaging several reconstructions #
##########################################################
sort_method: "variance/mean"
# 'mean_amplitude' or 'variance' or 'variance/mean' or 'volume', metric for averaging
averaging_space: "reciprocal_space"  # 'direct_space' or 'reciprocal_space'
correlation_threshold: 0.90
###################################
# parameters related to centering #
####################################
roll_modes: [0, 0, 0]
# axis=(0, 1, 2), correct a roll of few pixels
# after the decomposition into modes in PyNX
centering_method: "max_com"
# dictionary with the centering methods for direct and reciprocal space, e.g.
# {"direct_space": "max_com", "reciprocal_space": "max"}. The methods supported are
# 'com' (center of mass), 'max', 'max_com' (max along the first axis, center of mass in
# the detector plane), 'skip'. If a simple string is provided, it will use that method
# for both direct and reciprocal space.
#########################################################
# parameters relative to the FFT window and voxel sizes #
#########################################################
original_size: [252, 420, 392]  # size of the FFT array sent to phase retrieval.
# It will be modified to take into account binning during phasing automatically.
# Leave it to () if the shape did not change.
phasing_binning: [1, 1, 1]  # binning factor applied during phase retrieval
preprocessing_binning: [1, 1, 1]
# binning factors in each dimension used in preprocessing (not phase retrieval)
output_size: [100, 100, 100]
# (z, y, x) Fix the size of the output array, leave None to use the object size
keep_size: False  # True to keep the initial array size for orthogonalization (slower)
# it will be cropped otherwise
fix_voxel: 6  # voxel size in nm for the interpolation during the geometrical
# transformation. If a single value is provided, the voxel size will be identical is
# all 3 directions. Set it to None to use the default voxel size
# (calculated from q values, it will be different in each dimension).
################################################
# parameters related to the strain calculation #
################################################
data_frame: "detector"
# 'crystal' if the data was interpolated into the crystal frame using (xrayutilities) or
# (transformation matrix + align_q=True)
# 'laboratory' if the data was interpolated into the laboratory frame using
# the transformation matrix (align_q: False)
# 'detector' if the data is still in the detector frame
ref_axis_q: "y"
# axis along which q will be aligned (data_frame= 'detector' or 'laboratory')
# or is already aligned (data_frame='crystal')
save_frame: "crystal"  # 'crystal', 'laboratory' or 'lab_flat_sample'
# 'crystal' to save the data with q aligned along ref_axis_q
# 'laboratory' to save the data in the laboratory frame (experimental geometry)
# 'lab_flat_sample' to save the data in the laboratory frame,
# with all sample angles rotated back to 0. The rotations for 'laboratory' and
# 'lab_flat_sample' are realized after the strain calculation
# (which is done in the crystal frame along ref_axis_q)
isosurface_strain: 0.3  # threshold use for removing the outer layer
# (strain is undefined at the exact surface voxel)
skip_unwrap: False
# If 'skip_unwrap', it will not unwrap the phase. It can be used when there is a defect
# and phase unwrapping does not work well.
strain_method: "default"  # 'default' or 'defect'.
# If 'defect', will offset the phase in a loop and keep the smallest
# magnitude value for the strain.
# See: F. Hofmann et al. PhysRevMaterials 4, 013801 (2020)
######################################
# define beamline related parameters #
######################################
beamline: "ID01"  # name of the beamline, used for data loading and normalization
# by monitor and orthogonalisation
# supported beamlines: 'ID01', 'ID01BLISS', 'SIXS_2018', 'SIXS_2019', 'CRISTAL', 'P10', '34ID'
is_series: True  # specific to series measurement at P10
actuators: None
# Optional dictionary that can be used to define the entries
# corresponding to actuators in data files
# (useful at CRISTAL where the location of data keeps changing)
# e.g.  {'rocking_angle': 'actuator_1_3', 'detector': 'data_04', 'monitor': 'data_05'}
rocking_angle: "outofplane"  # "outofplane" for a sample rotation around x outboard,
# "inplane" for a sample rotation
# around y vertical up, does not matter for energy scan
#  "inplane" e.g. phi @ ID01, mu @ SIXS "outofplane" e.g. eta @ ID01
detector_distance: 0.50678  # 1.26  # sample to detector distance in m
energy: 9000  # x-ray energy in eV, 6eV offset at ID01
beam_direction: [1, 0, 0]
# incident beam along z, in the frame (z downstream, y vertical up, x outboard)
bragg_peak: None  # [127, 214, 316]  # list of three integers, position of the Bragg peak on the unbinned
# and full-sized detector. It will be used to calculate the real detector angles for the
# measured Bragg peak. Leave None to determine the Bragg peak position automatically.
direct_beam: [208, 154]  # [vertical, horizontal]
# direct beam position on the unbinned, full detector measured
# with detector angles given by dirbeam_detector_angles. It will be used to calculate
# the real detector angles for the measured Bragg peak. Leave None for no correction.
dirbeam_detector_angles: [0, 0]  # [outofplane, inplane] detector angles in degrees
# for the direct beam measurement. Leave None for no correction
outofplane_angle: None # 35.3627   # detector angle in deg (rotation around x outboard):
# delta ID01, delta SIXS, gamma 34ID
# this is the true angle, corrected for the direct beam position
inplane_angle: None # 0.4864  # detector angle in deg(rotation around y vertical up):
# nu ID01, gamma SIXS, delta 34ID
# this is the true angle, corrected for the direct beam position
tilt_angle: None  # angular step size for rocking angle, eta ID01, mu SIXS,
# does not matter for energy scan
sample_offsets: [90, 0, 0]
# tuple of offsets in degrees of the sample for each sample circle (outer first).
# the sample offsets will be subtracted to the motor values. Leave None if no offset.
specfile_name: "l5.spec"
# string or list of strings for multiple scans.
# template for ID01 and 34ID: name of the spec file if it is at the default location
# (in root_folder) or full path to the spec file
# template for SIXS: full path of the alias dictionnary or None to use the one in the
# package folder
# for P10, either None (if you are using the same directory structure as the beamline)
# or the full path to the .fio file
# template for all other beamlines: None
##########################
# setup for custom scans #
##########################
custom_scan: False  # set it to True for a stack of images acquired without scan,
# e.g. with ct in a macro, or when
# there is no spec/log file available, or for 34ID
custom_motors: {
    "delta": inplane_angle,
    "gamma": outofplane_angle,
    "theta": 1.0540277,
    "phi": -4.86,
}
###############################
# detector related parameters #
###############################
detector: "Maxipix"  # "Eiger2M", "Maxipix", "Eiger4M", "Merlin", "Timepix" or "Dummy"
custom_pixelsize: None
# use this to declare the pixel size of the "Dummy" detector if different from 55e-6
center_roi_x: None  # horizontal pixel number of the center of the ROI for data
# loading, leave None to use the full detector
center_roi_y: None  # vertical pixel number of the center of the ROI for data
# loading, leave None to use the full detector
roi_detector: None
# [Vstart, Vstop, Hstart, Hstop]. If "center_roi_x" or "center_roi_y" are not None,
# it will consider that the current values in roi_detector define a window around the
# pixel [center_roi_y, center_roi_x] and the final output will be
# [center_roi_y - roi_detector[0], center_roi_y + roi_detector[1],
# center_roi_x - roi_detector[2], center_roi_x + roi_detector[3]].
# leave None to use the full detector.
# Use with center_fft='skip' if you want this exact size.
template_imagefile: "data_mpx4_%05d.edf.gz"
# string or list of strings for multiple scans.
# template for ID01: 'data_mpx4_%05d.edf.gz' or 'align_eiger2M_%05d.edf.gz'
# template for ID01BLISS: 'ihhc3715_sample5.h5'
# template for SIXS_2018: 'align.spec_ascan_mu_%05d.nxs'
# template for SIXS_2019: 'spare_ascan_mu_%05d.nxs'
# template for Cristal: 'S%d.nxs'
# template for P10: '_master.h5'
# template for NANOMAX: '%06d.h5'
# template for 34ID: 'Sample%dC_ES_data_51_256_256.npz'
###################################################
# parameters related to the refraction correction #
###################################################
correct_refraction: False  # True for correcting the phase shift due to refraction
optical_path_method: "threshold"
# 'threshold' or 'defect', if 'threshold' it uses isosurface_strain to define the
# support  for the optical path calculation, if 'defect' (holes) it tries to remove
# only outer layers even if
# the amplitude is lower than isosurface_strain inside the crystal
dispersion: 4.1184E-05  # delta
# Pt:  3.0761E-05 @ 10300eV, 5.0328E-05 @ 8170eV
# 3.2880E-05 @ 9994eV, 4.1184E-05 @ 8994eV, 5.2647E-05 @ 7994eV,
# 4.6353E-05 @ 8500eV / Ge 1.4718E-05 @ 8keV
threshold_unwrap_refraction: 0.05  # threshold used to calculate the optical path
# the threshold for refraction/absorption corrections should be low,
# to correct for an object larger than the real one,
# otherwise it messes up the phase
###################################
# parameters related to the phase #
###################################
simulation: False  # set to True if it is a simulation, the parameter invert_phase
# will be set to 0 (see below)
invert_phase: True  # True for the displacement to have the right sign
# (FFT convention), False only for simulations
flip_reconstruction: True  # True if you want to get the conjugate object
phase_ramp_removal: "gradient"
# 'gradient'  # 'gradient' or 'upsampling', 'gradient' is much faster
threshold_gradient: 1.0
# upper threshold of the gradient of the phase, use for ramp removal
phase_offset: 0  # manual offset to add to the phase, should be 0 in most cases
phase_offset_origin: None
# the phase at this voxel will be set to phase_offset, None otherwise
offset_method: "mean"  # 'com' or 'mean', method for determining the phase offset origin
############################################
# parameters related to data visualization #
############################################
debug: False  # set to True to show all plots for debugging
align_axis: False  # for visualization, if True rotates the crystal to align
# axis_to_align along ref_axis after the
# calculation of the strain
ref_axis: "y"  # will align axis_to_align to that axis
axis_to_align: [-0.011662456997498807, 0.957321364700986, -0.28879022106682123]
# axis to align with ref_axis in the order x y z (axis 2, axis 1, axis 0)
strain_range: 0.002  # for plots
phase_range: 1.5  # for plots
grey_background: True  # True to set the background to grey in phase and strain plots
tick_spacing: 50  # for plots, in nm
tick_direction: "inout"  # 'out', 'in', 'inout'
tick_length: 3  # 10  # in plots
tick_width: 1  # 2  # in plots
#########################################
# parameters for temperature estimation #
#########################################
get_temperature: False  # only available for platinum at the moment
reflection: [1, 1, 1]
# measured reflection, use for estimating the temperature
reference_spacing: None  # for calibrating the thermal expansion,
# if None it is fixed to 3.9236/norm(reflection) Pt
reference_temperature: None
# used to calibrate the thermal expansion, if None it is fixed to 293.15K (RT)
#################################################
# parameters for phase averaging or apodization #
#################################################
half_width_avg_phase: 0
# (width-1)/2 of the averaging window for the phase, 0 means no phase averaging
apodize: False  # True to multiply the diffraction pattern by a filtering window
apodization_window: "blackman"
# filtering window, multivariate 'normal' or 'tukey' or 'blackman'
apodization_mu: [0.0, 0.0, 0.0]  # mu of the gaussian window
apodization_sigma: [0.30, 0.30, 0.30]  # sigma of the gaussian window
apodization_alpha: [1.0, 1.0, 1.0]  # shape parameter of the tukey window
################################
# parameters related to saving #
################################
save_rawdata: False  # True to save the amp-phase.vti before orthogonalization
save_support: False
# True to save the non-orthogonal support for later phase retrieval
save: True  # True to save amp.npz, phase.npz, strain.npz and vtk files
##################################
# end of user-defined parameters #
##################################